---
title       : Supplement to ModernDive textbook
description : To supplement learning of the material covered at http://moderndive.com, this chapter provides a playground for you to work with the code and better understand what each of the gray chunks of R code throughout the book does.

--- type:NormalExercise lang:r xp:0 skills:1 key:fa48676309


*** =instructions

- All of the needed packages from the textbook are available to you here.  Note that the `View` function will not work on DataCamp as it does in RStudio, but I have added interactive versions of many of the data frames below and this simulates the `View` function well.

<center>
[ModernDive data frames](https://ismayc.github.io/Effective-Data-Storytelling-using-the-tidyverse/moderndive.html)
</center>

<br>

- Please use this as a playground to answer the Learning Checks throughout the [ModernDive](http://moderndive.com) textbook.  There are no problems to complete here, but please do play around as needed!

- Remember to use the `library` function to load any needed package given at the top of the chapters of the [ModernDive](http://moderndive.com) textbook.

- Pressing the **Submit Answer** button will run all of the code in **script.R** in your **R Console**.  If you'd like to test things out, feel free to use the **R Console** directly.

*** =pre_exercise_code
```{r}
# Week 03 Thurs
library(tidyverse)
library(nycflights13)
library(fivethirtyeight)
library(gapminder)
total_fertility <- readr::read_csv("https://ismayc.github.io/soc301_s2017/slides/data/total_fertility.csv") 
colnames(total_fertility)[1] <- "country"
total_fertility <- total_fertility %>% 
  select(country, `1945`:`2015`) %>% 
  na.omit()
simple_ex <-
  data_frame(
    A = c(1, 2, 3, 4),
    B = c(1, 2, 3, 4),
    C = c(3, 2, 1, 2),
    D = c("a", "a", "b", "b")
  )
set.seed(3)
total_fert_tidy <- total_fertility %>% 
  sample_n(6) %>% 
  gather(-country, key = "year", value = "fert") %>% 
  mutate(year = as.numeric(year)) 
gap2007 <- gapminder %>% filter(year == 2007)

# Week 03 Tues
ideology <- read_csv("http://bit.ly/ideology-csv")
police_join <- inner_join(x = police_locals, y = ideology, 
                          by = "city")
dem_score <- read_csv("https://ismayc.github.io/soc301_s2017/slides/data/dem_score.csv")


## ModernDive.com

# Chapter 3

joined_flights <- inner_join(x = flights, y = airlines, by = "carrier")

# Chapter 4

all_alaska_flights <- flights %>% filter(carrier == "AS")
early_january_weather <- weather %>% 
  filter(origin == "EWR" & month == 1 & day <= 15)
flights_table <- flights %>% dplyr::count(carrier)
flights_namedports <- flights %>% 
  inner_join(airports, by = c("origin" = "faa"))

```
