---
title: "police_tidy"
output: html_document
---

```{r setup, include=FALSE}
library(DT)
library(readr)
library(tidyr)
#library(moderndive)
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(fivethirtyeight)
data(police_locals)
library(dplyr)
ideology <- read_csv("http://ismayc.github.io/Effective-Data-Storytelling-using-the-tidyverse/datasets/ideology.csv")
police_join <- inner_join(x = police_locals, y = ideology, by = "city")
cost_of_living <- read_csv("http://s3.amazonaws.com/assets.datacamp.com/production/course_3085/datasets/cost_of_living.csv")
police_join_cost <- inner_join(x = police_join, y = cost_of_living, by = "state")
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
police_tidy <- police_join_cost %>% 
  gather(key = "race", value = "reside_perc", all:asian) %>% 
  filter(race %in% c("white", "non_white")) %>% 
  mutate(col_group = factor(col_group, levels = c("high", "mid", "low")))
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
datatable(police_tidy,
  class = 'cell-border stripe',
  rownames = FALSE,
  filter = list(position = 'top'),
  options = list(pageLength = nrow(police_tidy), 
    autoWidth = TRUE,
    bInfo = FALSE,
    paging = FALSE))
```

